CREATE TABLE IF NOT EXISTS `screenshot` (
  `Id` INTEGER PRIMARY KEY,
  `FileExtension` TEXT NOT NULL,
  `FilePath` TEXT NOT NULL,
  `FileName` TEXT NOT NULL,
  `FileSize` REAL NOT NULL,
  `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `LastUpdatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `DeletedAt` DATETIME DEFAULT NULL,
  `DeleteAfter` DATETIME DEFAULT NULL,
  `CheckSum` TEXT UNIQUE NOT NULL,
  `MimeType` TEXT,
  `Source` TEXT NOT NULL,
  `Width` INTEGER,
  `Height` INTEGER
);

CREATE TABLE IF NOT EXISTS `game_note` (
  `Id` TEXT NOT NULL PRIMARY KEY,
  `Title` TEXT,
  `Content` TEXT,
  `ImagePath` TEXT,
  `GameId` TEXT,
  `SessionId` TEXT,
  `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `LastUpdatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `DeletedAt` DATETIME DEFAULT NULL,
  `DeleteAfter` DATETIME DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS `playnite_library_metrics` (
  `Id` INTEGER NOT NULL PRIMARY KEY,
  `Timestamp` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `TotalPlaytimeSeconds` REAL NOT NULL DEFAULT 0,
  `TotalGames` INTEGER NOT NULL DEFAULT 0,
  `VisibleTotalPlaytimeSeconds` REAL NOT NULL DEFAULT 0,
  `VisibleTotalGames` INTEGER NOT NULL DEFAULT 0,
  `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `LastUpdatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `synchronization_id` (
  `Id` INTEGER PRIMARY KEY CHECK (Id = 1),
  `SyncId` TEXT NOT NULL,
  `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `LastUsedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);