packages:
  - playnite-insights
  - playwright
  - packages/@playnite-insights/lib
  - packages/@playnite-insights/infra
  - packages/@playnite-insights/core
  - packages/@playnite-insights/testing
  - packages/@playatlas/auth
  - packages/@playatlas/game-library
  - packages/@playatlas/game-note
  - packages/@playatlas/game-session
  - packages/@playatlas/common
  - packages/@playatlas/system
  - packages/@playatlas/bootstrap
  - packages/@playatlas/playnite-integration
  - packages/integration-testing

catalog:
  '@faker-js/faker': ^9.9.0
  '@types/node': ^24.0.14
  sharp: ^0.34.3
  typescript: ^5.9.3
  ulid: ^3.0.2
  vitest: ^3.2.4
  zod: ^4.3.6

catalogs:
  busboy1:
    '@types/busboy': ^1.5.4
    busboy: ^1.6.0
  svelte5:
    '@sveltejs/adapter-node': ^5.2.12
    '@sveltejs/kit': ^2.16.0
    '@sveltejs/vite-plugin-svelte': ^5.0.0
    svelte: ^5.0.0
    svelte-check: ^4.0.0
  tailwind4:
    '@tailwindcss/typography': ^0.5.15
    '@tailwindcss/vite': ^4.0.0
    tailwindcss: ^4.0.0

ignoredBuiltDependencies:
  - sharp

injectWorkspacePackages: true

supportedArchitectures:
  cpu: [x64]
  libc: [glibc]
  os: [linux]
