BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS `tag` (
  `Id` TEXT NOT NULL PRIMARY KEY,
  `PlayniteId` TEXT UNIQUE DEFAULT NULL,
  `Name` TEXT NOT NULL,
  `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `LastUpdatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `DeletedAt` DATETIME DEFAULT NULL,
  `DeleteAfter` DATETIME DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS `game_tag` (
  `GameId` TEXT NOT NULL,
  `TagId` TEXT NOT NULL,
  PRIMARY KEY (`GameId`, `TagId`),
  FOREIGN KEY (`GameId`) REFERENCES `game`(`Id`),
  FOREIGN KEY (`TagId`) REFERENCES `tag`(`Id`)
);

UPDATE `game` SET `ContentHash` = '<INVALIDATED>';

COMMIT;