BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS `job` (
  `Id` TEXT PRIMARY KEY,
  `Type` TEXT NOT NULL,
  `Payload` TEXT NOT NULL,
  `Status` TEXT NOT NULL,
  `Attempts` INTEGER NOT NULL DEFAULT 0,
  `MaxAttempts` INTEGER NOT NULL DEFAULT 3,
  `Priority` INTEGER NOT NULL DEFAULT 0,
  `RunAt` DATETIME NOT NULL,
  `LockedAt` DATETIME DEFAULT NULL,
  `WorkerId` TEXT DEFAULT NULL,
  `LastError` TEXT DEFAULT NULL,
  `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `LastUpdatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `DeletedAt` DATETIME DEFAULT NULL,
  `DeleteAfter` DATETIME DEFAULT NULL
);

CREATE INDEX idx_jobs_pick
  ON `job` (`Status`, `RunAt`, `Priority`, `CreatedAt`);

COMMIT;