BEGIN TRANSACTION;

ALTER TABLE `playnite_game`
ADD COLUMN `LastUpdatedAt` TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `playnite_game`
ADD COLUMN `DeletedAt` TEXT DEFAULT NULL;
ALTER TABLE `playnite_game`
ADD COLUMN `DeleteAfter` TEXT DEFAULT NULL;

ALTER TABLE `company`
ADD COLUMN `LastUpdatedAt` TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `company`
ADD COLUMN `DeletedAt` TEXT DEFAULT NULL;
ALTER TABLE `company`
ADD COLUMN `DeleteAfter` TEXT DEFAULT NULL;

ALTER TABLE `completion_status`
ADD COLUMN `LastUpdatedAt` TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `completion_status`
ADD COLUMN `DeletedAt` TEXT DEFAULT NULL;
ALTER TABLE `completion_status`
ADD COLUMN `DeleteAfter` TEXT DEFAULT NULL;

ALTER TABLE `genre`
ADD COLUMN `LastUpdatedAt` TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `genre`
ADD COLUMN `DeletedAt` TEXT DEFAULT NULL;
ALTER TABLE `genre`
ADD COLUMN `DeleteAfter` TEXT DEFAULT NULL;

ALTER TABLE `platform`
ADD COLUMN `LastUpdatedAt` TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `platform`
ADD COLUMN `DeletedAt` TEXT DEFAULT NULL;
ALTER TABLE `platform`
ADD COLUMN `DeleteAfter` TEXT DEFAULT NULL;

COMMIT;