import { alternatives, plural, type ScoreEngineRegexLexicon } from "../../engine.language.lexicon";

export const RUN_BASED_ENGINE_LEXICON_EN = {
	SUBJECT_PRONOUN: alternatives("he", "she", "you"),
	RUN: alternatives(
		plural("run", "loop", "cycle", "playthrough", "journey", "adventure", "session"),
	),
	RESTART: alternatives("restart(?:ed|ing|s)?", "repeat(?:ed|ing|s)?"),
	LOOP: alternatives("every\\s+time", "when", "whenever", "each\\s+time"),
	POSSESSIVE: alternatives("her", "his", "your", "the"),
	WORLD: alternatives(
		plural("map", "world", "level", "dungeon", "planet", "castle", "universe", "layout"),
		"nive(?:l|is)",
	),
	DIE: alternatives("die(?:s|ed)?", "fail(?:s|ed)?"),
	DEATH: alternatives("(?:a\\s+)morte", "(?:a\\s+)falha"),
	PROCEDURALLY: alternatives("procedurally"),
	PROCEDURAL: alternatives("procedural"),
	REPETITION: alternatives("every", "each"),
	CREATE: alternatives("generat(?:ed|ing|e|s|es)", "creat(?:ed|ing|e|s|es)"),
	RANDOM: alternatives(plural("aleatori(?:o|os|a|as)")),
	RANDOMLY: alternatives("aleatoriamente", "de\\s+maneira\\s+aleatoria"),
	EVER_CHANGING: alternatives(
		"em\\s+constante\\s+mudanca",
		"(?:sempre\\s+)mud(?:a|ando|am)",
		"mud(?:a|am)\\s+constantemente",
	),
	TRY_AGAIN: alternatives("try\\s+again", "start\\s+over"),
	ENVIRONMENT: alternatives(plural("environment")),
	LOOT: alternatives("ite(?:m|ns)", "loot", plural("drop")),
	LOOT_VOLUME_NUMERIC: alternatives("\\d+\\+?\\s+itens"),
	ENEMY: alternatives("inimig(?:o|os)"),
	ENEMY_VOLUME_NUMERIC: alternatives("\\d+\\+?\\s+inimig(?:o|os)"),
	SAME: alternatives("igual", "igual\\s+(?:a|ao)\\s+outr(?:a|o)"),
	DIFFERENT: alternatives("diferente", "unica"),
	BUILD_ITEMS: alternatives(
		"armas",
		"itens",
		"habilidades",
		"equipamentos",
		"poderes",
		"cartas",
		"melhorias",
	),
	VARIETY: alternatives(
		plural("divers(?:a|o)", "vari(?:o|a)", "multipl(?:o|a)", "diferente"),
		"variedade",
		"diversidade",
	),
} as const satisfies ScoreEngineRegexLexicon;
