import type { PatternUnitTestSample } from "../../../test/pattern-unit-test-sample.types";
import {
	RUN_BASED_ENGINE_PATTERN_DICTIONARY_EN as PATTERN,
	type RunBasedPatternIdEN,
} from "../regex/en.pattern.dictionary";

export const runBasedPatternUniTestSampleEN = {
	EVER_CHANGING_ENVIRONMENT: {
		pattern: PATTERN.EVER_CHANGING_ENVIRONMENT,
		shouldMatch: [
			"ever-changing environment",
			"ever changing world",
			"constantly changing dungeons",
		],
		shouldNotMatch: [
			"the computer changed",
			"change your graphical settings",
			"ever-changing personality",
			"constantly changing spells",
		],
	},
	DYNAMIC_WORLD_GENERATION: {
		pattern: PATTERN.DYNAMIC_WORLD_GENERATION,
		shouldMatch: ["dynamic world generation", "dynamic map generation", "dynamic level creation"],
		shouldNotMatch: [
			"procedural editor",
			"procedurally generated dungeon",
			"procedural solution",
			"procedural algorithm",
		],
	},
	DIE_AND_TRY_AGAIN: {
		pattern: PATTERN.DIE_AND_TRY_AGAIN,
		shouldMatch: ["die, try again", "fail and start over", "fail, then try again"],
		shouldNotMatch: ["he tried to run"],
	},
	BETWEEN_RUNS: {
		pattern: PATTERN.BETWEEN_RUNS,
		shouldMatch: ["between runs", "between cycles", "between sessions"],
		shouldNotMatch: ["between intervals", "between earth and the sun"],
	},
	PROCEDURALLY_GENERATED_WORLD_STRONG: {
		pattern: PATTERN.PROCEDURALLY_GENERATED_WORLD_STRONG,
		shouldMatch: [
			"procedurally created world",
			"procedurally generated map",
			"procedurally created planet",
			"procedurally generated dungeon",
			"the entire map is procedurally generated",
			"all dungeons are generated procedurally",
			"a procedurally generated world",
			"a procedurally generated open world",
			"procedurally generated levels",
			"the world is generated procedurally",
			"each dungeon is procedurally generated",
			"explore procedurally generated planets",
			"features fully procedurally generated maps",
			"maps are created procedurally",
			"every run features a procedurally generated layout",
			"infinite procedurally generated universe",
		],
		shouldNotMatch: [
			"all dungeon are generated",
			"the world is beautifully generated",
			"the dungeon is carefully created",
			"maps are generated daily",
			"the planet was created by ancient gods",
			"the world is randomly selected",
			"the dungeon is randomly placed",
			"the map is automatically generated",
			"new dungeons are generated every week",
			"the dungeon is massive and filled with enemies. the system was procedurally optimized to generate loot tables.",
		],
	},
	PROCEDURALLY_GENERATED_WORLD_WEAK: {
		pattern: PATTERN.PROCEDURALLY_GENERATED_WORLD_WEAK,
		shouldMatch: [
			"procedurally created world",
			"procedurally generated map",
			"procedurally created planet",
			"procedurally generated dungeon",
			"the entire map is procedurally generated",
			"all dungeons are generated procedurally",
			"a procedurally generated world",
			"a procedurally generated open world",
			"procedurally generated levels",
			"the world is generated procedurally",
			"each dungeon is procedurally generated",
			"explore procedurally generated planets",
			"features fully procedurally generated maps",
			"maps are created procedurally",
			"the game creates its world procedurally",
			"every run features a procedurally generated layout",
			"infinite procedurally generated universe",
		],
		shouldNotMatch: [
			"all dungeon are generated",
			"the world is beautifully generated",
			"the dungeon is carefully created",
			"maps are generated daily",
			"the planet was created by ancient gods",
			"the world is randomly selected",
			"the dungeon is randomly placed",
			"the map is automatically generated",
			"new dungeons are generated every week",
			"the dungeon is massive and filled with enemies. the system was procedurally optimized to generate loot tables.",
		],
	},
	PROCEDURAL_WORLD: {
		pattern: PATTERN.PROCEDURAL_WORLD,
		shouldMatch: ["procedural world", "procedural map", "procedural dungeon"],
		shouldNotMatch: [
			"procedural editor",
			"procedurally generated dungeon",
			"procedural solution",
			"procedural algorithm",
		],
	},
	RANDOM_WORLDS: {
		pattern: PATTERN.RANDOM_WORLDS,
		shouldMatch: ["random world", "randomized map", "randomized dungeons", "unpredictable layouts"],
		shouldNotMatch: [
			"procedural editor",
			"procedurally generated dungeon",
			"procedural solution",
			"procedural algorithm",
		],
	},
	RANDOMLY_CREATED_WORLDS: {
		pattern: PATTERN.RANDOMLY_CREATED_WORLDS,
		shouldMatch: [
			"randomly generated worlds",
			"randomly created dungeons",
			"randomly generated maps",
			"dynamically created levels",
		],
		shouldNotMatch: ["the system was randomly restarting", "the computer restarted randomly"],
	},
	RESTART_AFTER_DEATH: {
		pattern: PATTERN.RESTART_AFTER_DEATH,
		shouldMatch: [
			"forced to restart her journey every time she dies",
			"restart your journey every time you die",
			"restart his journey every time he fails",
			"restart the cycle every time you die",
		],
		shouldNotMatch: [
			"restart the computer every time it dies",
			"restart the printer each time it doesn't connect",
		],
	},
	RUN_AFTER_RUN: {
		pattern: PATTERN.RUN_AFTER_RUN,
		shouldMatch: ["run after run", "cycle after cycle", "loop after loop"],
		shouldNotMatch: ["each run"],
	},
	RUN_REPETITION: {
		pattern: PATTERN.RUN_REPETITION,
		shouldMatch: [
			"every run",
			"every journey",
			"each journey",
			"each session",
			"each playthrough",
			"each new cycle",
			"every new adventure",
			"every subsequent cycle",
		],
		shouldNotMatch: [
			"a cada inimigo",
			"em cada fase da história",
			"outra arma",
			"cada personagem é único",
			"every runner",
		],
	},
	RUN_RESTARTS_ON_DEATH: {
		pattern: PATTERN.RUN_RESTARTS_ON_DEATH,
		shouldMatch: [
			"run restarts on death",
			"session restarts on failure",
			"the playthrough restarts when you die",
			"cycle ends when you die",
		],
		shouldNotMatch: [
			"he restarted his computer",
			"the computer was restarted",
			"they failed to restart the computer",
			"someone restarted the system after failure",
		],
	},
	TRY_AGAIN: {
		pattern: PATTERN.TRY_AGAIN,
		shouldMatch: ["try again", "start over"],
		shouldNotMatch: ["he tried to run"],
	},
	EVER_CHANGING: {
		pattern: PATTERN.EVER_CHANGING,
		shouldMatch: ["ever changing", "ever-changing", "constantly changing"],
		shouldNotMatch: ["you've changed", "someone changed the operating system"],
	},
	FRESH_LAYOUT_EVERY_RUN: {
		pattern: PATTERN.FRESH_LAYOUT_EVERY_RUN,
		shouldMatch: ["fresh layout each run", "fresh layout every session"],
		shouldNotMatch: ["fresh layout every time", "fresh new OS layout", "fresh software layout"],
	},
} as const satisfies PatternUnitTestSample<RunBasedPatternIdEN>;
