import type { PatternUnitTestSample } from "../../../test/pattern-unit-test-sample.types";
import {
	RUN_BASED_ENGINE_PATTERN_DICTIONARY_EN as PATTERN,
	type RunBasedPatternIdEN,
} from "../regex/en.pattern.dictionary";

export const runBasedPatternUniTestSampleEN = {
	ROGUELIKE_LITE: {
		pattern: PATTERN.ROGUELIKE_LITE,
		shouldMatch: ["roguelike", "roguelite", "rogue-like", "rogue-lite", "roguevania"],
		shouldNotMatch: ["horror", "run-based"],
	},
	UNIQUE_BUILDS: {
		pattern: PATTERN.UNIQUE_BUILDS,
		shouldMatch: ["unique builds", "different builds"],
		shouldNotMatch: ["unique items", "random items", "unique computer", "different person"],
	},
	BETWEEN_RUNS: {
		pattern: PATTERN.BETWEEN_RUNS,
		shouldMatch: ["between runs", "between cycles", "between sessions"],
		shouldNotMatch: ["between intervals", "between earth and the sun"],
	},
	PROCEDURALLY_GENERATED_WORLD_STRONG: {
		pattern: PATTERN.PROCEDURALLY_GENERATED_WORLD_STRONG,
		shouldMatch: [
			"procedurally created world",
			"procedurally generated map",
			"procedurally created planet",
			"procedurally generated dungeon",
			"the entire map is procedurally generated",
			"all dungeons are generated procedurally",
			"a procedurally generated world",
			"a procedurally generated open world",
			"procedurally generated levels",
			"the world is generated procedurally",
			"each dungeon is procedurally generated",
			"explore procedurally generated planets",
			"features fully procedurally generated maps",
			"maps are created procedurally",
			"every run features a procedurally generated layout",
			"infinite procedurally generated universe",
		],
		shouldNotMatch: [
			"all dungeon are generated",
			"the world is beautifully generated",
			"the dungeon is carefully created",
			"maps are generated daily",
			"the planet was created by ancient gods",
			"the world is randomly selected",
			"the dungeon is randomly placed",
			"the map is automatically generated",
			"new dungeons are generated every week",
			"the dungeon is massive and filled with enemies. the system was procedurally optimized to generate loot tables.",
			"procedurally optimized loot tables",
			"procedurally balanced enemies",
			"procedurally generated soundtrack",
			"procedurally animated character",
			"procedurally generated system",
		],
	},
	PROCEDURALLY_GENERATED_WORLD_WEAK: {
		pattern: PATTERN.PROCEDURALLY_GENERATED_WORLD_WEAK,
		shouldMatch: [
			"procedurally created world",
			"procedurally generated map",
			"procedurally created planet",
			"procedurally generated dungeon",
			"the entire map is procedurally generated",
			"all dungeons are generated procedurally",
			"a procedurally generated world",
			"a procedurally generated open world",
			"procedurally generated levels",
			"the world is generated procedurally",
			"each dungeon is procedurally generated",
			"explore procedurally generated planets",
			"features fully procedurally generated maps",
			"maps are created procedurally",
			"the game creates its world procedurally",
			"every run features a procedurally generated layout",
			"infinite procedurally generated universe",
			"the game procedurally generates its world",
			"worlds are procedurally generated in this game",
			"levels get generated procedurally",
		],
		shouldNotMatch: [
			"all dungeon are generated",
			"the world is beautifully generated",
			"the dungeon is carefully created",
			"maps are generated daily",
			"the planet was created by ancient gods",
			"the world is randomly selected",
			"the dungeon is randomly placed",
			"the map is automatically generated",
			"new dungeons are generated every week",
			"the dungeon is massive and filled with enemies. the system was procedurally optimized to generate loot tables.",
			"procedurally generated loot",
			"procedurally generated enemies",
			"procedurally generated system files",
		],
	},
	RANDOM_WORLDS: {
		pattern: PATTERN.RANDOM_WORLDS,
		shouldMatch: ["random world", "randomized map", "randomized dungeons", "unpredictable layouts"],
		shouldNotMatch: [
			"procedural editor",
			"procedurally generated dungeon",
			"procedural solution",
			"procedural algorithm",
			"procedural world generation",
			"procedurally generated world",
		],
	},
	RANDOMLY_CREATED_WORLDS: {
		pattern: PATTERN.RANDOMLY_CREATED_WORLDS,
		shouldMatch: [
			"randomly generated worlds",
			"randomly created dungeons",
			"randomly generated maps",
			"dynamically created levels",
		],
		shouldNotMatch: ["the system was randomly restarting", "the computer restarted randomly"],
	},
	RUN_AFTER_RUN: {
		pattern: PATTERN.RUN_AFTER_RUN,
		shouldMatch: ["run after run", "cycle after cycle", "loop after loop"],
		shouldNotMatch: ["each run", "run after him", "run after the ball"],
	},
	RUN_REPETITION: {
		pattern: PATTERN.RUN_REPETITION,
		shouldMatch: [
			"every run",
			"every journey",
			"each journey",
			"each session",
			"each playthrough",
			"each new cycle",
			"every new adventure",
			"every subsequent cycle",
			"every single new run",
		],
		shouldNotMatch: [
			"a cada inimigo",
			"em cada fase da história",
			"outra arma",
			"cada personagem é único",
			"every runner",
		],
	},
	EVER_CHANGING: {
		pattern: PATTERN.EVER_CHANGING,
		shouldMatch: ["ever changing", "ever-changing", "constantly changing"],
		shouldNotMatch: [
			"you've changed",
			"someone changed the operating system",
			"ever so beautiful",
			"he is changing",
		],
	},
} as const satisfies PatternUnitTestSample<RunBasedPatternIdEN>;
