import type { PatternUnitTestSample } from "../../../test/pattern-unit-test-sample.types";
import {
	RUN_BASED_ENGINE_PATTERN_DICTIONARY_PT as PATTERN,
	type RunBasedPatternIdPT,
} from "../regex/pt.pattern.dictionary";

export const runBasedPatternUniTestSamplePT = {
	CONSTANTLY_CHANGING_BUILD_ITEMS: {
		pattern: PATTERN.CONSTANTLY_CHANGING_BUILD_ITEMS,
		shouldMatch: [
			"habilidades que mudam constantemente",
			"armas em constante mudança",
			"equipamentos que sempre mudam",
		],
		shouldNotMatch: ["aquela pessoa está em constante mudança", "o sistema muda constantemente"],
	},
	DEATH_RESTARTS_YOUR_RUN: {
		pattern: PATTERN.DEATH_RESTARTS_YOUR_RUN,
		shouldMatch: [
			"a morte reinicia a sua run",
			"a morte reinicia o seu ciclo",
			"a falha reinicia sua run",
			"a morte reinicia a partida",
		],
		shouldNotMatch: ["a morte é inevitável"],
	},
	DIE_AND_TRY_AGAIN: {
		pattern: PATTERN.DIE_AND_TRY_AGAIN,
		shouldMatch: [
			"morra e tente novamente",
			"falhe e tente de novo",
			"morra e tente uma segunda vez",
			"morra, e então tente novamente",
		],
		shouldNotMatch: ["ele tentou ligar o computador novamente"],
	},
	EACH_RUN_IS_DIFFERENT: {
		pattern: PATTERN.EACH_RUN_IS_DIFFERENT,
		shouldMatch: ["cada partida é diferente", "cada partida é única", "cada ciclo é único"],
		shouldNotMatch: ["toda partida é a mesma"],
	},
	ENDLESS_WAYS_TO_COMBINE_BUILD_ITEMS: {
		pattern: PATTERN.ENDLESS_WAYS_TO_COMBINE_BUILD_ITEMS,
		shouldMatch: [
			"maneiras praticamente ilimitadas de combinar suas habilidades",
			"formas ilimitadas de combinar seus poderes",
			"maneiras sem limites de combinar seus equipamentos",
			"formas ilimitadas de combinar sinergias",
			"maneiras sem limites de combinar suas sinergias",
			"maneiras sem limites de combinar seus feitiços",
			"formas ilimitadas de combinar encantamentos",
			"formas ilimitadas de combinar estilos de jogo",
			"formas ilimitadas de combinar estilos de gameplay",
			"maneiras ilimitadas de combinar estrategias",
			"maneiras infinitas de combinar estrategias",
			"maneiras infinitas de criar estrategias",
			"infinitas maneiras de combinar sinergias",
			"dezenas de formas diferentes de combinar estratégias",
			"milhares de maneiras distintas de combinar estilos de jogo",
			"centenas de jeitos distintos de montar estratégias",
			"centenas de jeitos distintos de criar estratégias",
			"milhares de formas diferentes de criar sinergias",
		],
		shouldNotMatch: ["aquela pessoa está em constante mudança", "o sistema muda constantemente"],
	},
	ENEMY_VOLUME_SPECIFIC: {
		pattern: PATTERN.ENEMY_VOLUME_SPECIFIC,
		shouldMatch: ["450+ inimigos", "120 inimigos", "mais que 400+ inimigos", "mais de 10 inimigos"],
		shouldNotMatch: [
			"120 fases",
			"60 fps",
			"100 níveis",
			"100+ níveis",
			"mais de 200 dungeons",
			"450 jogadores",
			"10 horas de gameplay",
			"itens variados",
			"itens únicos",
			"itens especiais",
			"loot raro",
			"colecione itens",
			"mais de 100 horas de jogo",
			"10% de desconto",
			"versão 1.2",
			"até 4 jogadores",
			"modo 2D",
			"120 colecionáveis",
			"100 cartas",
			"50 armas",
			"200 habilidades",
			"+344 itens",
		],
	},
	EVER_CHANGING_ENVIRONMENT: {
		pattern: PATTERN.EVER_CHANGING_ENVIRONMENT,
		shouldMatch: [
			"ambientes em constante mudança",
			"ambiente em constante mudança",
			"ambientes que sempre mudam",
		],
		shouldNotMatch: [
			"o ruído ambiente está mais alto que o normal",
			"o ruído ambiente está mudando constantemente",
		],
	},
	EVER_CHANGING_WORLDS: {
		pattern: PATTERN.EVER_CHANGING_WORLDS,
		shouldMatch: [
			"fases em constante mudança",
			"fases que estão em constante mudança",
			"mundo sempre mudando",
			"mundo que está sempre mudando",
			"mapa que sempre muda",
			"dungeon em constante mudança",
			"fase que muda constantemente",
		],
		shouldNotMatch: ["aquela pessoa está em contante mudança", "pessoas que sempre muda"],
	},
	EVER_CHANGING: {
		pattern: PATTERN.EVER_CHANGING,
		shouldMatch: ["em constante mudança", "sempre mudando"],
		shouldNotMatch: ["sempre alternando"],
	},
	LOOT_VOLUME_SPECIFIC: {
		pattern: PATTERN.LOOT_VOLUME_SPECIFIC,
		shouldMatch: [
			"450+ itens",
			"mais que 450 itens",
			"120 itens",
			"mais que 400+ itens",
			"mais de 10 itens",
		],
		shouldNotMatch: [
			"120 fases",
			"300 inimigos",
			"60 fps",
			"100 níveis",
			"100+ níveis",
			"mais de 200 dungeons",
			"450 jogadores",
			"10 horas de gameplay",
			"itens variados",
			"itens únicos",
			"itens especiais",
			"loot raro",
			"colecione itens",
			"mais de 100 horas de jogo",
			"10% de desconto",
			"versão 1.2",
			"até 4 jogadores",
			"modo 2D",
			"120 colecionáveis",
			"100 cartas",
			"50 armas",
			"200 habilidades",
		],
	},
	NO_RUN_IS_THE_SAME: {
		pattern: PATTERN.NO_RUN_IS_THE_SAME,
		shouldMatch: [
			"nenhuma run é igual",
			"nenhuma partida é igual",
			"nenhum ciclo é igual ao outro",
			"nenhuma partida será igual a outra",
			"nenhuma partida é igual à outra",
		],
		shouldNotMatch: ["a cada partida", "a cada ciclo"],
	},
	PROCEDURALLY_GENERATED_WORLD: {
		pattern: PATTERN.PROCEDURALLY_GENERATED_WORLD,
		shouldMatch: [
			"mundo gerado proceduralmente",
			"mapa gerado proceduralmente",
			"planeta gerado de maneira procedural",
			"planeta gerado de forma procedural",
			"mundo totalmente gerado proceduralmente",
			"mundo gerado totalmente de forma procedural",
			"mapa aleatoriamente gerado proceduralmente",
			"um planeta inteiro gerado de forma procedural",
			"cada run tem um mapa gerado proceduralmente",
			"a dungeon é gerada de maneira procedural a cada partida",
			"o jogo cria mundos gerados proceduralmente",
			"as dungeons são geradas de maneira procedural",
			"mapa gerado de forma procedural",
			"o mundo é gerado de maneira procedural",
			"os planetas são gerados proceduralmente",
		],
		shouldNotMatch: [
			"o relatório foi gerado proceduralmente pelo sistema",
			"um erro foi gerado proceduralmente",
			"o mapa mostra o mundo inteiro",
			"viajar pelo mundo gera experiências",
			"o mundo muda quando algo é gerado",
			"um mapa aparece quando o arquivo é gerado",
			"código gerado proceduralmente pelo compilador",
			"conteúdo gerado proceduralmente para testes",
			"um mundo de problemas foi gerado",
			"isso gerou um mapa mental",
			"o sistema reinicia quando um erro é gerado",
			"o computador gera um mapa de memória ao reiniciar",
		],
	},
	RANDOM_ENEMY: {
		pattern: PATTERN.RANDOM_ENEMY,
		shouldMatch: ["inimigos aleatórios", "inimigo aleatório"],
		shouldNotMatch: ["itens aleatórios", "loot aleatório"],
	},
	RANDOM_LOOT: {
		pattern: PATTERN.RANDOM_LOOT,
		shouldMatch: [
			"loot aleatório",
			"itens aleatórios",
			"recompensas aleatórias",
			"drops aleatórios",
		],
		shouldNotMatch: ["os itens do inventário são aleatórios"],
	},
	RANDOM_WORLDS: {
		pattern: PATTERN.RANDOM_WORLDS,
		shouldMatch: ["fases aleatórias", "níveis aleatórios", "mapas aleatórios"],
		shouldNotMatch: ["situações aleatórias", "pessoas aleatórias"],
	},
	RANDOMLY_CREATED_WORLDS: {
		pattern: PATTERN.RANDOMLY_CREATED_WORLDS,
		shouldMatch: [
			"mapas gerados aleatoriamente",
			"mapas gerados randomicamente",
			"mapas gerados de forma randômica",
			"níveis gerados aleatoriamente",
			"fases geradas de maneira aleatória",
			"dungeons geradas de forma dinâmica",
			"castelos gerados de maneira dinâmica",
		],
		shouldNotMatch: ["situações são aleatórias", "pessoas que são aleatórias"],
	},
	RESTART_AFTER_DEATH: {
		pattern: PATTERN.RESTART_AFTER_DEATH,
		shouldMatch: [
			"recomeçar toda vez que morre",
			"recomece sempre que morrer",
			"reiniciar toda vez que morre",
			"recomeçar toda vez que morrer",
			"recomeçar toda vez que ela morre",
			"recomeçar toda vez que ele morre",
			"reiniciar sempre que morre",
			"recomeçar sempre que falhar",
			"reinicie sempre que falhar",
			"recomeçar sempre que ele falhar",
		],
		shouldNotMatch: ["reiniciar o computador sempre que morre a bateria"],
	},
	RUN_AFTER_RUN: {
		pattern: PATTERN.RUN_AFTER_RUN,
		shouldMatch: ["partida após partida", "ciclo após ciclo", "sessão após sessão"],
		shouldNotMatch: ["a cada partida"],
	},
	RUN_REPETITION: {
		pattern: PATTERN.RUN_REPETITION,
		shouldMatch: [
			"a cada partida",
			"a cada ciclo único",
			"a cada nova partida",
			"a cada sessão",
			"a cada nova run",
			"a cada nova tentativa",
			"a cada novo ciclo",
			"a cada nova sessão",
			"a cada próxima run",
			"entre sessões",
			"em cada ciclo",
			"por cada run",
			"outra tentativa",
		],
		shouldNotMatch: [
			"a cada inimigo",
			"em cada fase da história",
			"outra arma",
			"cada personagem é único",
		],
	},
	RUN_RESTARTS_ON_DEATH: {
		pattern: PATTERN.RUN_RESTARTS_ON_DEATH,
		shouldMatch: [
			"a run reinicia ao morrer",
			"a sessão reinicia quando você morrer",
			"a sessão reinicia quando você morre",
		],
		shouldNotMatch: ["a morte é inevitável"],
	},
	TRY_AGAIN: {
		pattern: PATTERN.TRY_AGAIN,
		shouldMatch: ["tente novamente", "tente de novo", "tente uma segunda vez"],
		shouldNotMatch: ["ele tentou ligar o computador novamente"],
	},
	UNIQUE_BUILDS: {
		pattern: PATTERN.UNIQUE_BUILDS,
		shouldMatch: [
			"builds únicas",
			"configurações únicas",
			"configurações poderosas",
			"build diferente",
			"builds diferente",
			"diferentes builds",
			"variedade de builds",
			"centenas de builds diferentes",
			"dezenas de builds únicas",
			"dezenas de builds distintas",
		],
		shouldNotMatch: [
			"configurações diferentes",
			"diferentes configurações gráficas",
			"diferentes configurações de hardware",
			"configurações avançadas",
		],
	},
	VARIETY_OF_BUILD_ITEMS: {
		pattern: PATTERN.VARIETY_OF_BUILD_ITEMS,
		shouldMatch: [
			"diversidade de habilidades",
			"diversas habilidades",
			"vários equipamentos",
			"variedade de armas",
			"diversas melhorias",
		],
		shouldNotMatch: ["vários sistemas", "diversos computadores"],
	},
} as const satisfies PatternUnitTestSample<RunBasedPatternIdPT>;
