import type { PatternUnitTestSample } from "../../../test/pattern-unit-test-sample.types";
import {
	RUN_BASED_ENGINE_PATTERN_DICTIONARY_PT as PATTERN,
	type RunBasedPatternIdPT,
} from "../regex/pt.pattern.dictionary";

export const runBasedPatternUniTestSamplePT = {
	ROGUELIKE_LITE: {
		pattern: PATTERN.ROGUELIKE_LITE,
		shouldMatch: ["roguelike", "roguelite", "rogue-like", "rogue-lite", "roguevania"],
		shouldNotMatch: ["horror", "run-based"],
	},
	EVER_CHANGING: {
		pattern: PATTERN.EVER_CHANGING,
		shouldMatch: ["em constante mudança", "sempre mudando"],
		shouldNotMatch: ["sempre alternando"],
	},
	PROCEDURALLY_GENERATED_WORLD: {
		pattern: PATTERN.PROCEDURALLY_GENERATED_WORLD,
		shouldMatch: [
			"mundo gerado proceduralmente",
			"mapa gerado proceduralmente",
			"planeta gerado de maneira procedural",
			"planeta gerado de forma procedural",
			"mundo totalmente gerado proceduralmente",
			"mundo gerado totalmente de forma procedural",
			"mapa aleatoriamente gerado proceduralmente",
			"um planeta inteiro gerado de forma procedural",
			"cada run tem um mapa gerado proceduralmente",
			"a dungeon é gerada de maneira procedural a cada partida",
			"o jogo cria mundos gerados proceduralmente",
			"as dungeons são geradas de maneira procedural",
			"mapa gerado de forma procedural",
			"o mundo é gerado de maneira procedural",
			"os planetas são gerados proceduralmente",
		],
		shouldNotMatch: [
			"o relatório foi gerado proceduralmente pelo sistema",
			"um erro foi gerado proceduralmente",
			"o mapa mostra o mundo inteiro",
			"viajar pelo mundo gera experiências",
			"o mundo muda quando algo é gerado",
			"um mapa aparece quando o arquivo é gerado",
			"código gerado proceduralmente pelo compilador",
			"conteúdo gerado proceduralmente para testes",
			"um mundo de problemas foi gerado",
			"isso gerou um mapa mental",
			"o sistema reinicia quando um erro é gerado",
			"o computador gera um mapa de memória ao reiniciar",
		],
	},
	RANDOM_WORLDS: {
		pattern: PATTERN.RANDOM_WORLDS,
		shouldMatch: ["fases aleatórias", "níveis aleatórios", "mapas aleatórios"],
		shouldNotMatch: ["situações aleatórias", "pessoas aleatórias"],
	},
	RANDOMLY_CREATED_WORLDS: {
		pattern: PATTERN.RANDOMLY_CREATED_WORLDS,
		shouldMatch: [
			"mapas gerados aleatoriamente",
			"mapas gerados randomicamente",
			"mapas gerados de forma randômica",
			"níveis gerados aleatoriamente",
			"fases geradas de maneira aleatória",
			"dungeons geradas de forma dinâmica",
			"castelos gerados de maneira dinâmica",
		],
		shouldNotMatch: ["situações são aleatórias", "pessoas que são aleatórias"],
	},
	RUN_AFTER_RUN: {
		pattern: PATTERN.RUN_AFTER_RUN,
		shouldMatch: ["partida após partida", "ciclo após ciclo", "sessão após sessão"],
		shouldNotMatch: ["a cada partida"],
	},
	RUN_REPETITION: {
		pattern: PATTERN.RUN_REPETITION,
		shouldMatch: [
			"a cada partida",
			"a cada ciclo único",
			"a cada nova partida",
			"a cada sessão",
			"a cada nova run",
			"a cada nova tentativa",
			"a cada novo ciclo",
			"a cada nova sessão",
			"a cada próxima run",
			"entre sessões",
			"em cada ciclo",
			"por cada run",
			"outra tentativa",
		],
		shouldNotMatch: [
			"a cada inimigo",
			"em cada fase da história",
			"outra arma",
			"cada personagem é único",
		],
	},
	UNIQUE_BUILDS: {
		pattern: PATTERN.UNIQUE_BUILDS,
		shouldMatch: [
			"builds únicas",
			"configurações únicas",
			"configurações poderosas",
			"build diferente",
			"builds diferente",
			"diferentes builds",
			"variedade de builds",
			"centenas de builds diferentes",
			"dezenas de builds únicas",
			"dezenas de builds distintas",
		],
		shouldNotMatch: [
			"configurações diferentes",
			"diferentes configurações gráficas",
			"diferentes configurações de hardware",
			"configurações avançadas",
		],
	},
} as const satisfies PatternUnitTestSample<RunBasedPatternIdPT>;
